### PR TITLE
Add support for scala 2.13

### PR DESCRIPTION
**Pull request by tmccombs**

### CODE REVIEW

**Comment by aappddeevv** [comment]
Is this pushed? I see the 2.12 version but no 2.13 on maven.

**Comment by tmccombs** [comment]
@aappddeevv I just merged it. But it has not been deployed to maven yet.

**Comment by aappddeevv** [comment]
Is there anything holding up a maven push of the 2.13 version?

**Comment by tmccombs** [comment]
It's published to maven central now

**Pull request merged**
